// data.js
const products = [
    {
        id: 1,
        title: 'Chaqueta de Cuero "Monarch"',
        brand: 'Celzimo Veste',
        price: 349990,
        category: 'chaquetas',
        image: 'jacket.png',
        description: 'Chaqueta de cuero genuino con acabados de primera calidad. Perfecta para un look elegante y moderno, con detalles metálicos sutiles que aportan un toque distintivo. Forro interior de seda suave.',
        sizes: ['S', 'M', 'L', 'XL'],
        discount: 40,
        promoText: 'WEEK SALE',
        colors: ['jacket.png', 'jacket.png', 'jacket.png', 'jacket.png', 'jacket.png', 'jacket.png'],
        availableDelivery: true,
        availableStore: true
    },
    {
        id: 2,
        title: 'Reloj Cronógrafo "Imperator"',
        brand: 'Celzimo Veste',
        price: 215500,
        category: 'accesorios',
        image: 'watch.png',
        description: 'Reloj cronógrafo de acero inoxidable, resistente al agua hasta 50 metros y con un diseño impecable. Maquinaria de precisión japonesa y cristal de zafiro antirayones.',
        sizes: ['Única'],
        colors: ['watch.png', 'watch.png'],
        availableDelivery: true,
        availableStore: false
    },
    {
        id: 3,
        title: 'Bolso de Mano "Aura"',
        brand: 'Celzimo Veste',
        price: 189990,
        category: 'accesorios',
        image: 'bag.png',
        description: 'Bolso de mano de diseño minimalista, amplio espacio interior y acabados en cuero artesanal. Cuenta con compartimentos internos para organización y correa ajustable.',
        sizes: ['Única'],
        discount: 20,
        promoText: 'CYBER DAY',
        colors: ['bag.png', 'bag.png', 'bag.png'],
        availableDelivery: true,
        availableStore: true
    },
    {
        id: 4,
        title: 'Gafas de Sol "Eclipse"',
        brand: 'Celzimo Veste',
        price: 95000,
        category: 'accesorios',
        image: 'sunglasses.png',
        description: 'Gafas de sol polarizadas con protección UV400. Marco ligero y resistente hecho de acetato premium. Diseño atemporal que favorece todo tipo de rostros.',
        sizes: ['Única'],
        colors: ['sunglasses.png'],
        availableDelivery: false,
        availableStore: true
    },
    {
        id: 5,
        title: 'Skinny Fit Indigo Jeans',
        brand: 'Palazzo del denim',
        price: 89990,
        category: 'jeans',
        image: 'jeans.png',
        description: 'Jeans corte skinny fit, tejido elástico para mayor comodidad y lavado azul oscuro clásico. Costuras reforzadas y botones de cobre grabados.',
        sizes: ['36', '38', '40', '42'],
        colors: ['jeans.png', 'jeans.png', 'jeans.png', 'jeans.png', 'jeans.png'],
        availableDelivery: true,
        availableStore: true
    },
    {
        id: 6,
        title: 'Straight Classic Blue',
        brand: 'Palazzo del denim',
        price: 95000,
        category: 'jeans',
        image: 'jeans.png',
        description: 'Jeans de corte recto clásico en tono azul. Ajuste perfecto y durabilidad excepcional. Un básico imprescindible en cualquier armario moderno.',
        sizes: ['36', '38', '40', '42', '44'],
        colors: ['jeans.png', 'jeans.png'],
        availableDelivery: true,
        availableStore: false
    },
    {
        id: 7,
        title: 'Relaxed Light Wash',
        brand: 'Palazzo del denim',
        price: 99990,
        category: 'jeans',
        image: 'jeans.png',
        description: 'Jeans holgados con lavado claro. Estilo relajado e ideal para el día a día. Denim 100% algodón de alta calidad con efecto desgastado natural.',
        sizes: ['38', '40', '42'],
        colors: ['jeans.png'],
        availableDelivery: true,
        availableStore: true
    }
];
